### ISSUE TITLE
this module cause TTFB Slow

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-widget-modules#24]
Because of this module the main admin page of whmcs (dashboard) cause to be very slow (+6s for total with the three of hexonet moduls: 
ispapi_account.php (800 ms delay)
ispapi_modules.php (4 s Delay)
ispapi_monitoring.php (2.5 s Delay)

please correct thease three moduls by adding a button to manualy prees for update the result of moduls....
thansk

**Comment by papakai** [comment]
Hey @HamidRadmani 

well, the account widget is connecting to the Hexonet API to get the account balance displayed. I guess, there's not much we can do there. Just maybe caching that data then for a certain time (TTL).

Modules Widget: it takes that long it has to load the latest version number from github for each module.
We can change the behavior to only check version numbers once a day and adding a button to request this on demand.

monitoring widget: it already has a button allowing you to deactivate it. you should just have it activated on purpose. Nothing we will change there. An idea could be to turn it on once a month and check the results and then turn it again off.

Ideas for the account and modules widget are noted down.
Thanks for addressing.

Kai

**Comment by HamidRadmani** [comment]
thanks for your reply
about the "account widget" it's good to cache it but a refresh button is better than caching because there is an accounting purpose.
Modules Widget; only check version numbers once a day and adding a button to request this on-demand is very good idea.
Monitoring widget; deactivate button cant reduce the loading time of dashboard page! only rename or deleting the "ispapi_monitoring.php" file, reduce 2.5 s loading time!

thank you
Radmani

**Comment by papakai** [comment]
@HamidRadmani thanks for additional feeback for the monitoring widget, something I've to check in addition then.

**Comment by papakai** [comment]
@HamidRadmani
Account Widget, please check [this update](https://github.com/hexonet/whmcs-ispapi-widget-account/releases/tag/v3.1.3).

**Comment by HamidRadmani** [comment]
I tested it right now!
woww! It works great! thanks.

**Comment by papakai** [comment]
@HamidRadmani the "Monitoring Widget" has been reviewed to follow the UI way using an icon to turn the widget on or off.
Still, data caching isn't possible here. I again suggest to keep that widget by default turned off. Use it maybe once a quarter.
There's a lot data being looked up from WHMCS DB and HEXONET API, then compared and issues displayed. Caching data makes no sense here, otherwise it might run into false positives just because of outdated data.

**Comment by papakai** [comment]
@HamidRadmani 
Modules Widget has been reviewed.

* It is not making data requests when disabled (using our status icon) or hidden (using that 'x' icon).
* output is more compact
* no logo requests happy any longer
* data is cached for 24h
* Icons added to access docs / deprecation notes
* ... further plans in the queue

https://github.com/hexonet/whmcs-ispapi-widget-modules/releases/tag/v2.3.0

Still, I have to finalize account and monitoring widget to follow this examplary review, but I guess your issue can be closed.

HTH

**Comment by HamidRadmani** [comment]
@papakai Thanks for updates and your hard work.
every thing is now perfect , expect "Domain Monitoring Widget"!
turning off the widget cant reduse TTFB, but renaming ispapi_monitoring.php (or deleting the module) Significantly reduces TTFB!
loading time of whmcs admin dashboard:

without Domain Monitoring Widget: 1.40s
Domain Monitoring Widget turne **off**: 3.50s
Domain Monitoring Widget turne **on**: 3.50s

**Comment by papakai** [comment]
Yes, there are things i have already noted down for review. This was one of the points. Just follow the upcoming releases of the account and monitoring widget.

**Comment by papakai** [comment]
@HamidRadmani my work is done. Again, you should keep that Domain Monitoring Widget turned off in general. Activate it once per quater to see, if there's  something wrong, fix things and then turn it again off. It makes multiple DB Queries and API Calls that are superfluous for the daily work and in addition we cannot cache them.

HTH

**Comment by HamidRadmani** [comment]
@papakai Thank you very much, everything work well with latest relases.
