### ISSUE TITLE
SSLCert Add-on cannot download from this module

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-widget-modules#29]
SSLCert Add-on cannot download from this module due to change from Hexonet to Centralnic

**Comment by KaiSchwarz-cnic** [comment]
Hi Hamid,

yes that's right and it also applies to the domain importer addon.
Something we have on radar. I am actually onboarding a new team mate, the right upcoming task for him.

Until then:

* [WHMCS SSLCert Addon](https://github.com/centralnic-reseller/whmcs-ssl/raw/master/whmcs-cnic-ssl-latest.zip)
* [WHMCS Domain Importer Addon](https://github.com/centralnic-reseller/whmcs-domainimporter/raw/master/whmcs-cnic-domainimport-latest.zip)
* [WHMCS DNS Addon](https://github.com/centralnic-reseller/whmcs-dns/raw/master/whmcs-cnic-dns-latest.zip) (DNS Templating)

Thanks for reporting.

Kai

**Comment by KaiSchwarz-cnic** [comment]
We have now updated in direction of the above addons via v2.3.3.
